version: '3.8'

services:
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: blogAppDb
      POSTGRES_USER: blogAppUser
      POSTGRES_PASSWORD: blogPass321
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U blogAppUser -d blogAppDb"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    image: 708895070110.dkr.ecr.ap-southeast-1.amazonaws.com/mcblog-be:latest
    ports:
      - "3001:3001"
    environment:
      DATABASE_URL: postgres://blogAppUser:blogPass321@postgres:5432/blogAppDb
      NODE_ENV: production
    depends_on:
      postgres:
        condition: service_healthy

  frontend:
    image: 708895070110.dkr.ecr.ap-southeast-1.amazonaws.com/mcblog-fe:latest
    ports:
      - "3000:3000"
    environment:
      REACT_APP_API_URL: "http://backend:3001"
    depends_on:
      - backend

volumes:
  postgres_data:
